# Vibration monitor configuration
tty_device=/dev/ttyUSB4
threshold=1.5
data_dir=/tmp/vibration_data
clear_events=true
get_sensor_cloud_url=https://sensor-key-retrieval-836427764358.northamerica-northeast2.run.app
get_sensor_api_key=0503opgPGRLyn2BG8MUlwLe09
vm_endpoint=http://35.184.73.192:2026/ingest
vm_api_key=AmberMonitoring2026!
device_id=94:83:C4:23:7D:1F
