# Vibration monitor configuration
tty_device=/dev/ttyUSB4
threshold=1.5
data_dir=/tmp/vibration_data
clear_events=true
cloud_function_url=https://insert-vibration-data-836427764358.northamerica-northeast2.run.app
api_key=0227sgqScirlvza2G3lfiZuQ87KA2
get_sensor_cloud_url=https://sensor-key-retrieval-836427764358.northamerica-northeast2.run.app
get_sensor_api_key=0503opgPGRLyn2BG8MUlwLe09
device_id=94:83:C4:23:7C:38
